component_management:
  default_rules:
    statuses:
      - type: project
        target: auto
      - type: patch
        target: auto
  individual_components:
    - component_id: server
      name: Server
      paths:
        - "apps/server/src/**"
    - component_id: config
      name: Config
      paths:
        - libs/config/src/**
    - component_id: web
      name: Web
      paths:
        - libs/web/src/**
    - component_id: utils
      name: Utils
      paths:
        - libs/util/src/**
    - component_id: all_tests
      name: All Tests
      paths:
        - "apps/*/test/**"
        - "libs/*/test/**"

comment:
  layout: diff, flags, components, files, header, footer
  hide_project_coverage: false
  show_carryforward_flags: true

test_analytics:
  flake_detection: true
